spring.application.name=full_project_spring_react
spring.datasource.url=jdbc:postgresql://localhost:5432/java_project
spring.datasource.username=postgres
spring.datasource.password=0795715252
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#to make search very good
spring.datasource.hikari.auto-commit=false
# Server port configuration

# ???? ???? ????? ????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080
